### ISSUE TITLE
Problems with sam commands and CloudFormation template

### ISSUE THREAD

**Issue by MXClyde** [aws-samples/lambdaedge-openidconnect-samples#11]
**Environment**

SAM CLI, version 1.16.0
aws-cli/1.18.69 Python/3.8.5 Linux/5.4.0-1039-azure botocore/1.16.19

**Issues**

- I was not able to deploy the CloudFormation template as-is, resulting in the error:

_Error: Failed to create changeset for the stack: oidc-auth, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Template error: instance of Fn::GetAtt references undefined resource LogBucketName_

**Resolution:** Removing the two sections in template.yaml referring to LogBucketName: lines 30-32 and lines 57-60.

- Execution of sam package and sam deploy as per the shell script at https://aws.amazon.com/blogs/networking-and-content-delivery/securing-cloudfront-distributions-using-openid-connect-and-aws-secrets-manager/ failed with error:

_botocore.exceptions.NoRegionError: You must specify a region._

**Resolution:** add the following regio specification to the sam package and deploy calls:

--region us-east-1

**Comment by tchinchow** [comment]
@MXClyde 
I believe that the template expects the region to be defined in your `~/.aws/config` file.

Now regarding the error about a wrong reference to the logging bucket _("Template error: instance of Fn::GetAtt references undefined resource LogBucketName")_, I also ran against this issue. You can work around it without completey removing the logging feature. Indeed, Just correct the reference and make it point to the correct bucket reference _(Use `LoggingBucket` instead of `LogBucketName`)_:

```yaml
Logging:
  Bucket: !GetAtt LoggingBucket.DomainName
```
